export const browserCoreExamples = [
  "openhedgehog browser status",
  "openhedgehog browser start",
  "openhedgehog browser stop",
  "openhedgehog browser tabs",
  "openhedgehog browser open https://example.com",
  "openhedgehog browser focus abcd1234",
  "openhedgehog browser close abcd1234",
  "openhedgehog browser screenshot",
  "openhedgehog browser screenshot --full-page",
  "openhedgehog browser screenshot --ref 12",
  "openhedgehog browser snapshot",
  "openhedgehog browser snapshot --format aria --limit 200",
  "openhedgehog browser snapshot --efficient",
  "openhedgehog browser snapshot --labels",
];

export const browserActionExamples = [
  "openhedgehog browser navigate https://example.com",
  "openhedgehog browser resize 1280 720",
  "openhedgehog browser click 12 --double",
  'openhedgehog browser type 23 "hello" --submit',
  "openhedgehog browser press Enter",
  "openhedgehog browser hover 44",
  "openhedgehog browser drag 10 11",
  "openhedgehog browser select 9 OptionA OptionB",
  "openhedgehog browser upload /tmp/file.pdf",
  'openhedgehog browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "openhedgehog browser dialog --accept",
  'openhedgehog browser wait --text "Done"',
  "openhedgehog browser evaluate --fn '(el) => el.textContent' --ref 7",
  "openhedgehog browser console --level error",
  "openhedgehog browser pdf",
];
